### PR TITLE
Add System.Text.Json (de)serialization implementation

### PR DESCRIPTION
**Pull request by 01010101lzy**
This pull request implements a converter for serializing/deserializing `Ulid`s using `System.Text.Json` (`Utf8Json` reader/writer). To use that feature, I also multi-targeted the library to `netcoreapp3.0` and added some feature flags.

# Notes

I haven't finished changing the CircleCI script because I haven't got a CircleCI account. Might use a GitHub action to automate the testing instead.

### CODE REVIEW

**Comment by neuecc** [comment]
thanks, almost okay but implementation is not good.
I don't allow allocate string in serializing and deserializing.

For example, get the `ReadOnlySpan<byte>` in deserializing.

```csharp
if (reader.TokenType != JsonTokenType.String)
{
    throw new InvalidOperationException(); // TODO:msg
}

ReadOnlySpan<byte> span = stackalloc byte[0];
if (reader.HasValueSequence)
{
    //reader.va
    var seq = reader.ValueSequence;
    if (seq.IsSingleSegment)
    {
        span = seq.FirstSpan;
    }
    else
    {
        var len = seq.Length;
        if (len > 300) // TODO:300???
        {
            throw new InvalidOperationException();
        }
        Span<byte> stackSpan = stackalloc byte[(int)len];
        seq.CopyTo(stackSpan);
        span = stackSpan;
    }
}
else
{
    span = reader.ValueSpan;
}

// TODO:create Ulid
```

**Comment by 01010101lzy** [comment]
Got that. Will try implementing with spans.

**Comment by 01010101lzy** [comment]
Implemented. 

Tried to use existing methods but (sadly) they were for operating `char`s instead of `byte`s so I copied them and changed them into bytes. Is there a more elegant(?) way to do that?

**Comment by neuecc** [comment]
Ok, I'll merge and then, will modify your code.
First, perhaps separate the packages.
Ulid does not depend on System.Text.Json and will create a `Ulid.SystemTextJson` package.

**Comment by 01010101lzy** [comment]
Thanks!
________________________________

**Comment by neuecc** [comment]
I've uploaded `1.0.0` that includes your great contrib.

**Pull request merged**
