### PR TITLE
SIMD Speed improvement

### PR DESCRIPTION
**Pull request by aobatact**
Improved performance by using SIMD.

# Benchmark

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18362
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.100
  [Host]   : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT  [AttachedDebugger]
  ShortRun : .NET Core 3.1.0 (CoreCLR 4.700.19.56402, CoreFX 4.700.19.56404), X64 RyuJIT

Job=ShortRun  Jit=RyuJit  Platform=X64  
Runtime=.NET Core 3.1  IterationCount=1  LaunchCount=1  
WarmupCount=1  

```

## CompareTo

|   Method |      Mean | Error | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |----------:|------:|------:|-------:|------:|------:|----------:|
|    Guid_ |  4.623 ns |    NA |  1.00 |      - |     - |     - |         - |
| OldUlid_ |  6.996 ns |    NA |  1.51 |      - |     - |     - |         - |
|    Ulid_ |  1.603 ns |    NA |  0.35 |      - |     - |     - |         - |
|   NUlid_ | 14.918 ns |    NA |  3.23 | 0.0095 |     - |     - |      40 B |

## Equals

|   Method |      Mean | Error | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |----------:|------:|------:|-------:|------:|------:|----------:|
|    Guid_ |  1.472 ns |    NA |  1.00 |      - |     - |     - |         - |
| OldUlid_ |  1.792 ns |    NA |  1.22 |      - |     - |     - |         - |
|    Ulid_ |  1.546 ns |    NA |  1.05 |      - |     - |     - |         - |
|   NUlid_ | 27.557 ns |    NA | 18.72 | 0.0191 |     - |     - |      80 B |

## GetGuid

|   Method |      Mean | Error |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |----------:|------:|-------:|------:|------:|----------:|
| OldUlid_ |  7.092 ns |    NA |      - |     - |     - |         - |
|    Ulid_ |  1.209 ns |    NA |      - |     - |     - |         - |
|   NUlid_ | 12.843 ns |    NA | 0.0096 |     - |     - |      40 B |

## GetTime

|   Method |     Mean | Error | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |---------:|------:|------:|------:|------:|------:|----------:|
| OldUlid_ | 16.59 ns |    NA |  1.00 |     - |     - |     - |         - |
|    Ulid_ | 12.52 ns |    NA |  0.75 |     - |     - |     - |         - |

## NewToString
|   Method |     Mean | Error | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |---------:|------:|------:|-------:|------:|------:|----------:|
|    Guid_ | 178.8 ns |    NA |  1.00 | 0.0229 |     - |     - |      96 B |
| OldUlid_ | 127.9 ns |    NA |  0.72 | 0.0191 |     - |     - |      80 B |
|    Ulid_ | 123.5 ns |    NA |  0.69 | 0.0191 |     - |     - |      80 B |
|   NUlid_ | 279.3 ns |    NA |  1.56 | 0.1106 |     - |     - |     464 B |

### CODE REVIEW

**Comment by aobatact** [comment]
I tried to use SIMD in constructor `Ulid(long timestampMilliseconds, XorShift64 random)` , `Ulid(long timestampMilliseconds, ReadOnlySpan<byte> randomness)` and `GetHashCode()` but these were slower than current one.

**Comment by aobatact** [comment]
Finish vectorized constructor

## Bench NewToString
(commented out [Config(typeof(BenchmarkConfig))])
|   Method |     Mean |   Error |  StdDev | Ratio | RatioSD |
|--------- |---------:|--------:|--------:|------:|--------:|
|    Guid_ | 176.1 ns | 3.51 ns | 3.28 ns |  1.00 |    0.00 |
| OldUlid_ | 128.0 ns | 1.71 ns | 1.52 ns |  0.73 |    0.02 |
|    Ulid_ | 120.6 ns | 1.20 ns | 1.06 ns |  0.69 |    0.01 |
|   NUlid_ | 291.3 ns | 6.72 ns | 8.74 ns |  1.67 |    0.06 |

**Comment by aobatact** [comment]
I have some problem with `New` benchmark.
I wanted to compare the performance between old and new `Ulid.NewUlid()` but the bench as follows failed to run.

```csharp
extern alias Ulid_1_0_0;
extern alias newUlid;
using BenchmarkDotNet.Attributes;
using System;
using OldUlid = Ulid_1_0_0::System.Ulid;
using NewUlid = newUlid::System.Ulid;

namespace PerfBenchmark.Suite
{
    [Config(typeof(BenchmarkConfig))]
    public class New
    {
        [Benchmark(Baseline = true)]
        public Guid Guid_()
        {
            return Guid.NewGuid();
        }

        [Benchmark]
        public OldUlid OldUlid_()
        {
            return OldUlid.NewUlid();
        }        
        
        [Benchmark]
        public NewUlid Ulid_()
        {
            return NewUlid.NewUlid();
        }

        [Benchmark]
        public NUlid.Ulid NUlid_()
        {
            return NUlid.Ulid.NewUlid();
        }
    }
}
```

**Comment by neuecc** [comment]
thanks!
I'll check, please wait a moment.

**Comment by aobatact** [comment]
I've created more improvement commits.
Should I push here or should I create a new pull request?

**Comment by neuecc** [comment]
please push here!

**Comment by aobatact** [comment]
Improved by making members readonly
## CompareTo
|   Method |      Mean | Error | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |----------:|------:|------:|-------:|------:|------:|----------:|
|    Guid_ |  4.445 ns |    NA |  1.00 |      - |     - |     - |         - |
| OldUlid_ |  6.446 ns |    NA |  1.45 |      - |     - |     - |         - |
|    Ulid_ |  1.273 ns |    NA |  0.29 |      - |     - |     - |         - |
|   NUlid_ | 14.033 ns |    NA |  3.16 | 0.0095 |     - |     - |      40 B |

## Equals
|   Method |      Mean | Error | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |----------:|------:|------:|-------:|------:|------:|----------:|
|    Guid_ |  1.500 ns |    NA |  1.00 |      - |     - |     - |         - |
| OldUlid_ |  1.640 ns |    NA |  1.09 |      - |     - |     - |         - |
|    Ulid_ |  1.346 ns |    NA |  0.90 |      - |     - |     - |         - |
|   NUlid_ | 26.014 ns |    NA | 17.35 | 0.0191 |     - |     - |      80 B |

**Comment by aobatact** [comment]
It seems that optimized `Equals` is faster than the vectorized one 

## Vectorized Equals
|   Method |      Mean |     Error |    StdDev |    Median | Ratio | RatioSD |
|--------- |----------:|----------:|----------:|----------:|------:|--------:|
|    Guid_ |  1.427 ns | 0.0093 ns | 0.0082 ns |  1.425 ns |  1.00 |    0.00 |
| OldUlid_ |  1.750 ns | 0.0159 ns | 0.0141 ns |  1.744 ns |  1.23 |    0.01 |
|    Ulid_ |  1.551 ns | 0.0033 ns | 0.0029 ns |  1.551 ns |  1.09 |    0.01 |
|   NUlid_ | 25.181 ns | 0.5273 ns | 0.9096 ns | 24.701 ns | 17.79 |    0.67 |

## No Vectorized Equals

|   Method |      Mean |     Error |    StdDev | Ratio | RatioSD |
|--------- |----------:|----------:|----------:|------:|--------:|
|    Guid_ |  1.441 ns | 0.0228 ns | 0.0214 ns |  1.00 |    0.00 |
| OldUlid_ |  1.751 ns | 0.0181 ns | 0.0169 ns |  1.22 |    0.02 |
|    Ulid_ |  1.181 ns | 0.0163 ns | 0.0153 ns |  0.82 |    0.02 |
|   NUlid_ | 24.462 ns | 0.1369 ns | 0.1213 ns | 16.96 |    0.28 |

**Comment by aobatact** [comment]
I've done all the optimization I can think of it now.

**Comment by neuecc** [comment]
@aobatact 
I'm sorry to close PR by github-stale.
We were unable to conduct a review to determine if it was reasonable given the complexity.

**Pull request closed without merging**
